---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-providers-s3
  namespace: argocd
  labels:
    app.kubernetes.io/name: crossplane-providers-s3
    layer: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy após o core
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  
  source:
    repoURL: https://github.com/samuelBarreto/crossplane-system.git  # ALTERAR
    targetRevision: main
    path: providers/aws/s3
    directory:
      recurse: false  # Apenas arquivos na raiz, ignora subdiretórios

  
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  
  syncPolicy:
    automated:
      prune: false  # Desabilitado temporariamente para evitar deleção acidental
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  # Health check customizado para Providers
  ignoreDifferences:
  - group: pkg.crossplane.io
    kind: Provider
    jsonPointers:
    - /status

