---
# ArgoCD Application para gerenciar o próprio Ingress
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-ingress
    layer: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy logo no início
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  
  source:
    repoURL: https://github.com/your-org/crossplane-platform.git  # ALTERAR
    targetRevision: main
    path: argocd/ingress
    directory:
      # Apenas aplicar o ingress principal
      include: argocd-ingress.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

