---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: governance-gatekeeper
  namespace: argocd
  labels:
    app.kubernetes.io/name: gatekeeper
    layer: security
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # PRIMEIRO - Instala Gatekeeper
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  
  source:
    # Gatekeeper oficial
    repoURL: https://github.com/open-policy-agent/gatekeeper.git
    targetRevision: release-3.14
    path: deploy
  
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  # Aguardar Gatekeeper estar pronto antes de prosseguir
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle

